//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.04 at 02:58:57 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:oozie:hive2-action:1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uri.oozie.hive2_action._1;
