//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.04 at 02:58:57 PM CST 
//


package uri.oozie.workflow._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uri.oozie.workflow._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WorkflowApp_QNAME = new QName("uri:oozie:workflow:1.0", "workflow-app");
    private final static QName _Switch_QNAME = new QName("uri:oozie:workflow:1.0", "switch");
    private final static QName _Kill_QNAME = new QName("uri:oozie:workflow:1.0", "kill");
    private final static QName _MapReduce_QNAME = new QName("uri:oozie:workflow:1.0", "map-reduce");
    private final static QName _Pig_QNAME = new QName("uri:oozie:workflow:1.0", "pig");
    private final static QName _SubWorkflow_QNAME = new QName("uri:oozie:workflow:1.0", "sub-workflow");
    private final static QName _Fs_QNAME = new QName("uri:oozie:workflow:1.0", "fs");
    private final static QName _Java_QNAME = new QName("uri:oozie:workflow:1.0", "java");
    private final static QName _LAUNCHERMemoryMb_QNAME = new QName("uri:oozie:workflow:1.0", "memory.mb");
    private final static QName _LAUNCHERVcores_QNAME = new QName("uri:oozie:workflow:1.0", "vcores");
    private final static QName _LAUNCHERJavaOpts_QNAME = new QName("uri:oozie:workflow:1.0", "java-opts");
    private final static QName _LAUNCHEREnv_QNAME = new QName("uri:oozie:workflow:1.0", "env");
    private final static QName _LAUNCHERQueue_QNAME = new QName("uri:oozie:workflow:1.0", "queue");
    private final static QName _LAUNCHERSharelib_QNAME = new QName("uri:oozie:workflow:1.0", "sharelib");
    private final static QName _LAUNCHERViewAcl_QNAME = new QName("uri:oozie:workflow:1.0", "view-acl");
    private final static QName _LAUNCHERModifyAcl_QNAME = new QName("uri:oozie:workflow:1.0", "modify-acl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uri.oozie.workflow._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CREDENTIAL }
     * 
     */
    public CREDENTIAL createCREDENTIAL() {
        return new CREDENTIAL();
    }

    /**
     * Create an instance of {@link PARAMETERS }
     * 
     */
    public PARAMETERS createPARAMETERS() {
        return new PARAMETERS();
    }

    /**
     * Create an instance of {@link CONFIGURATION }
     * 
     */
    public CONFIGURATION createCONFIGURATION() {
        return new CONFIGURATION();
    }

    /**
     * Create an instance of {@link WORKFLOWAPP }
     * 
     */
    public WORKFLOWAPP createWORKFLOWAPP() {
        return new WORKFLOWAPP();
    }

    /**
     * Create an instance of {@link SWITCH }
     * 
     */
    public SWITCH createSWITCH() {
        return new SWITCH();
    }

    /**
     * Create an instance of {@link KILL }
     * 
     */
    public KILL createKILL() {
        return new KILL();
    }

    /**
     * Create an instance of {@link MAPREDUCE }
     * 
     */
    public MAPREDUCE createMAPREDUCE() {
        return new MAPREDUCE();
    }

    /**
     * Create an instance of {@link PIG }
     * 
     */
    public PIG createPIG() {
        return new PIG();
    }

    /**
     * Create an instance of {@link SUBWORKFLOW }
     * 
     */
    public SUBWORKFLOW createSUBWORKFLOW() {
        return new SUBWORKFLOW();
    }

    /**
     * Create an instance of {@link FS }
     * 
     */
    public FS createFS() {
        return new FS();
    }

    /**
     * Create an instance of {@link JAVA }
     * 
     */
    public JAVA createJAVA() {
        return new JAVA();
    }

    /**
     * Create an instance of {@link LAUNCHER }
     * 
     */
    public LAUNCHER createLAUNCHER() {
        return new LAUNCHER();
    }

    /**
     * Create an instance of {@link PREPARE }
     * 
     */
    public PREPARE createPREPARE() {
        return new PREPARE();
    }

    /**
     * Create an instance of {@link DELETE }
     * 
     */
    public DELETE createDELETE() {
        return new DELETE();
    }

    /**
     * Create an instance of {@link MKDIR }
     * 
     */
    public MKDIR createMKDIR() {
        return new MKDIR();
    }

    /**
     * Create an instance of {@link FLAG }
     * 
     */
    public FLAG createFLAG() {
        return new FLAG();
    }

    /**
     * Create an instance of {@link MOVE }
     * 
     */
    public MOVE createMOVE() {
        return new MOVE();
    }

    /**
     * Create an instance of {@link CHMOD }
     * 
     */
    public CHMOD createCHMOD() {
        return new CHMOD();
    }

    /**
     * Create an instance of {@link TOUCHZ }
     * 
     */
    public TOUCHZ createTOUCHZ() {
        return new TOUCHZ();
    }

    /**
     * Create an instance of {@link CHGRP }
     * 
     */
    public CHGRP createCHGRP() {
        return new CHGRP();
    }

    /**
     * Create an instance of {@link GLOBAL }
     * 
     */
    public GLOBAL createGLOBAL() {
        return new GLOBAL();
    }

    /**
     * Create an instance of {@link START }
     * 
     */
    public START createSTART() {
        return new START();
    }

    /**
     * Create an instance of {@link END }
     * 
     */
    public END createEND() {
        return new END();
    }

    /**
     * Create an instance of {@link DECISION }
     * 
     */
    public DECISION createDECISION() {
        return new DECISION();
    }

    /**
     * Create an instance of {@link CASE }
     * 
     */
    public CASE createCASE() {
        return new CASE();
    }

    /**
     * Create an instance of {@link DEFAULT }
     * 
     */
    public DEFAULT createDEFAULT() {
        return new DEFAULT();
    }

    /**
     * Create an instance of {@link FORKTRANSITION }
     * 
     */
    public FORKTRANSITION createFORKTRANSITION() {
        return new FORKTRANSITION();
    }

    /**
     * Create an instance of {@link FORK }
     * 
     */
    public FORK createFORK() {
        return new FORK();
    }

    /**
     * Create an instance of {@link JOIN }
     * 
     */
    public JOIN createJOIN() {
        return new JOIN();
    }

    /**
     * Create an instance of {@link ACTIONTRANSITION }
     * 
     */
    public ACTIONTRANSITION createACTIONTRANSITION() {
        return new ACTIONTRANSITION();
    }

    /**
     * Create an instance of {@link ACTION }
     * 
     */
    public ACTION createACTION() {
        return new ACTION();
    }

    /**
     * Create an instance of {@link STREAMING }
     * 
     */
    public STREAMING createSTREAMING() {
        return new STREAMING();
    }

    /**
     * Create an instance of {@link PIPES }
     * 
     */
    public PIPES createPIPES() {
        return new PIPES();
    }

    /**
     * Create an instance of {@link CREDENTIALS }
     * 
     */
    public CREDENTIALS createCREDENTIALS() {
        return new CREDENTIALS();
    }

    /**
     * Create an instance of {@link CREDENTIAL.Property }
     * 
     */
    public CREDENTIAL.Property createCREDENTIALProperty() {
        return new CREDENTIAL.Property();
    }

    /**
     * Create an instance of {@link PARAMETERS.Property }
     * 
     */
    public PARAMETERS.Property createPARAMETERSProperty() {
        return new PARAMETERS.Property();
    }

    /**
     * Create an instance of {@link CONFIGURATION.Property }
     * 
     */
    public CONFIGURATION.Property createCONFIGURATIONProperty() {
        return new CONFIGURATION.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WORKFLOWAPP }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WORKFLOWAPP }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "workflow-app")
    public JAXBElement<WORKFLOWAPP> createWorkflowApp(WORKFLOWAPP value) {
        return new JAXBElement<WORKFLOWAPP>(_WorkflowApp_QNAME, WORKFLOWAPP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SWITCH }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SWITCH }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "switch")
    public JAXBElement<SWITCH> createSwitch(SWITCH value) {
        return new JAXBElement<SWITCH>(_Switch_QNAME, SWITCH.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KILL }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KILL }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "kill")
    public JAXBElement<KILL> createKill(KILL value) {
        return new JAXBElement<KILL>(_Kill_QNAME, KILL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MAPREDUCE }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MAPREDUCE }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "map-reduce")
    public JAXBElement<MAPREDUCE> createMapReduce(MAPREDUCE value) {
        return new JAXBElement<MAPREDUCE>(_MapReduce_QNAME, MAPREDUCE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PIG }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PIG }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "pig")
    public JAXBElement<PIG> createPig(PIG value) {
        return new JAXBElement<PIG>(_Pig_QNAME, PIG.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SUBWORKFLOW }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SUBWORKFLOW }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "sub-workflow")
    public JAXBElement<SUBWORKFLOW> createSubWorkflow(SUBWORKFLOW value) {
        return new JAXBElement<SUBWORKFLOW>(_SubWorkflow_QNAME, SUBWORKFLOW.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FS }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FS }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "fs")
    public JAXBElement<FS> createFs(FS value) {
        return new JAXBElement<FS>(_Fs_QNAME, FS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JAVA }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JAVA }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "java")
    public JAXBElement<JAVA> createJava(JAVA value) {
        return new JAXBElement<JAVA>(_Java_QNAME, JAVA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "memory.mb", scope = LAUNCHER.class)
    public JAXBElement<Long> createLAUNCHERMemoryMb(Long value) {
        return new JAXBElement<Long>(_LAUNCHERMemoryMb_QNAME, Long.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "vcores", scope = LAUNCHER.class)
    public JAXBElement<Long> createLAUNCHERVcores(Long value) {
        return new JAXBElement<Long>(_LAUNCHERVcores_QNAME, Long.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "java-opts", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHERJavaOpts(String value) {
        return new JAXBElement<String>(_LAUNCHERJavaOpts_QNAME, String.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "env", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHEREnv(String value) {
        return new JAXBElement<String>(_LAUNCHEREnv_QNAME, String.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "queue", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHERQueue(String value) {
        return new JAXBElement<String>(_LAUNCHERQueue_QNAME, String.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "sharelib", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHERSharelib(String value) {
        return new JAXBElement<String>(_LAUNCHERSharelib_QNAME, String.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "view-acl", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHERViewAcl(String value) {
        return new JAXBElement<String>(_LAUNCHERViewAcl_QNAME, String.class, LAUNCHER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "uri:oozie:workflow:1.0", name = "modify-acl", scope = LAUNCHER.class)
    public JAXBElement<String> createLAUNCHERModifyAcl(String value) {
        return new JAXBElement<String>(_LAUNCHERModifyAcl_QNAME, String.class, LAUNCHER.class, value);
    }

}
