//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.04 at 02:58:57 PM CST 
//


package uri.oozie.workflow._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SUB-WORKFLOW complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SUB-WORKFLOW"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="app-path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="propagate-configuration" type="{uri:oozie:workflow:1.0}FLAG" minOccurs="0"/&gt;
 *         &lt;element name="configuration" type="{uri:oozie:workflow:1.0}CONFIGURATION" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SUB-WORKFLOW", propOrder = {
    "appPath",
    "propagateConfiguration",
    "configuration"
})
public class SUBWORKFLOW {

    @XmlElement(name = "app-path", required = true)
    protected String appPath;
    @XmlElement(name = "propagate-configuration")
    protected FLAG propagateConfiguration;
    protected CONFIGURATION configuration;

    /**
     * Gets the value of the appPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppPath() {
        return appPath;
    }

    /**
     * Sets the value of the appPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppPath(String value) {
        this.appPath = value;
    }

    /**
     * Gets the value of the propagateConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link FLAG }
     *     
     */
    public FLAG getPropagateConfiguration() {
        return propagateConfiguration;
    }

    /**
     * Sets the value of the propagateConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLAG }
     *     
     */
    public void setPropagateConfiguration(FLAG value) {
        this.propagateConfiguration = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIGURATION }
     *     
     */
    public CONFIGURATION getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIGURATION }
     *     
     */
    public void setConfiguration(CONFIGURATION value) {
        this.configuration = value;
    }

}
